# Generated by Django 4.2.10 on 2024-02-11 04:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('tags', jsonfield.fields.JSONField()),
                ('stock_status', models.BooleanField()),
                ('available_stock', models.IntegerField()),
            ],
        ),
    ]
